# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Calcifer
email: andry.tino@hotmail.com
description: > # A tutorial for creating your first cross-platform app with Cordova tools in Microsoft Visual Studio 2015
author: Andrea Tino
baseurl: "/t-calcifer" # the subpath of your site, e.g. /blog
url: "http://andry-tino.github.io" # the base hostname & protocol for your site
twitter_username: _atino
github_username:  andry-tino

# Build settings
markdown: kramdown
